# Generated by Django 6.0.5 on 2026-06-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_forwarded_by_alter_complaint_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reference_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
